version: '3.9'

services:

  # FRONTEND
  frontend:
    image: node:18
    container_name: smartcity-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - backend

  # BACKEND
  backend:
    image: node:18
    container_name: smartcity-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/smartcitydb
    ports:
      - "5000:5000"
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - mongo

  # MACHINE LEARNING SERVICE (Python-based)
  ml_service:
    image: python:3.11
    container_name: smartcity-ml
    working_dir: /app
    volumes:
      - ./ml:/app
    command: >
      sh -c "pip install -r requirements.txt && python main.py"
    depends_on:
      - backend

  # MONGO DATABASE
  mongo:
    image: mongo:6
    container_name: smartcity-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # REVERSE PROXY WITH NGINX
  nginx:
    image: nginx:latest
    container_name: smartcity-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
